#!/usr/bin/env python3
"""
NIS Core Toolkit - Component Creation
Creates agents, protocols, and other system components
"""

import subprocess
import sys
from pathlib import Path
from rich.console import Console
from rich.prompt import Prompt, Confirm

console = Console()

def create_agent(agent_name: str, agent_type: str = "reasoning"):
    """Create a new agent using NIS Agent Toolkit"""
    
    # Check if we're in a NIS project
    if not Path("config/project.yaml").exists():
        console.print("âŒ Not in a NIS project directory", style="red")
        console.print("Run 'nis init' to create a new project first")
        return False
    
    # Check if agents directory exists
    agents_dir = Path("agents")
    if not agents_dir.exists():
        agents_dir.mkdir()
    
    agent_dir = agents_dir / agent_name
    if agent_dir.exists():
        console.print(f"âŒ Agent '{agent_name}' already exists", style="red")
        return False
    
    console.print(f"í´– Creating {agent_type} agent: {agent_name}", style="bold blue")
    
    # Create agent directory
    agent_dir.mkdir()
    
    # Create agent template based on type
    templates = {
        "reasoning": create_reasoning_agent_template,
        "vision": create_vision_agent_template,
        "memory": create_memory_agent_template,
        "action": create_action_agent_template
    }
    
    if agent_type not in templates:
        console.print(f"âŒ Unknown agent type: {agent_type}", style="red")
        console.print(f"Available types: {list(templates.keys())}")
        return False
    
    # Generate agent code
    templates[agent_type](agent_dir, agent_name)
    
    console.print(f"âœ… Agent '{agent_name}' created successfully!", style="bold green")
    console.print(f"í³ Location: {agent_dir}")
    console.print(f"í³ Edit {agent_dir}/{agent_name}.py to customize behavior")
    
    return True

def create_reasoning_agent_template(agent_dir: Path, agent_name: str):
    """Create a reasoning agent with Chain of Thought capabilities"""
    
    agent_file = agent_dir / f"{agent_name}.py"
    agent_file.write_text(f'''#!/usr/bin/env python3
"""
{agent_name} - Reasoning Agent
Generated by NIS Core Toolkit
"""

import logging
from typing import Dict, Any, List
from datetime import datetime

class {agent_name.replace('-', '_').title()}Agent:
    """
    Reasoning agent with Chain of Thought capabilities
    
    This is a working implementation - no hype, just practical reasoning
    """
    
    def __init__(self, agent_id: str = "{agent_name}"):
        self.agent_id = agent_id
        self.logger = logging.getLogger(f"agent.{{agent_id}}")
        self.memory = []
        self.tools = {{
            "calculator": self._calculator,
            "text_analysis": self._analyze_text
        }}
    
    def observe(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """Observe and process input data"""
        observation = {{
            "timestamp": datetime.now().isoformat(),
            "input": input_data,
            "agent_id": self.agent_id
        }}
        
        self.logger.info(f"Observing: {{input_data}}")
        return observation
    
    def think(self, observation: Dict[str, Any]) -> Dict[str, Any]:
        """Chain of Thought reasoning process"""
        
        # Step 1: Analyze the problem
        problem = observation.get("input", {{}}).get("problem", "")
        
        chain_of_thought = []
        chain_of_thought.append(f"Problem: {{problem}}")
        
        # Step 2: Break down the problem
        if "calculate" in problem.lower():
            chain_of_thought.append("This appears to be a calculation problem")
            chain_of_thought.append("I should use the calculator tool")
        elif "analyze" in problem.lower():
            chain_of_thought.append("This appears to be an analysis problem")  
            chain_of_thought.append("I should use text analysis")
        else:
            chain_of_thought.append("This is a general reasoning problem")
            chain_of_thought.append("I'll apply logical reasoning")
        
        # Step 3: Plan solution approach
        chain_of_thought.append("Planning solution approach...")
        
        reasoning = {{
            "chain_of_thought": chain_of_thought,
            "confidence": 0.8,  # Honest confidence assessment
            "reasoning_type": "analytical"
        }}
        
        self.logger.info(f"Reasoning: {{reasoning}}")
        return reasoning
    
    def act(self, reasoning: Dict[str, Any]) -> Dict[str, Any]:
        """Take action based on reasoning"""
        
        # Simple action based on reasoning
        action = {{
            "timestamp": datetime.now().isoformat(),
            "action_type": "reasoning_response",
            "confidence": reasoning.get("confidence", 0.5),
            "chain_of_thought": reasoning.get("chain_of_thought", []),
            "result": "Reasoning process completed"
        }}
        
        # Store in memory for future reference
        self.memory.append(action)
        
        self.logger.info(f"Action taken: {{action}}")
        return action
    
    def _calculator(self, expression: str) -> float:
        """Simple calculator tool"""
        try:
            # Basic safety check - only allow numbers and basic operators
            safe_chars = set("0123456789+-*/.()")
            if not all(c in safe_chars for c in expression.replace(" ", "")):
                raise ValueError("Invalid characters in expression")
            
            result = eval(expression)
            return float(result)
        except Exception as e:
            self.logger.error(f"Calculator error: {{e}}")
            return 0.0
    
    def _analyze_text(self, text: str) -> Dict[str, Any]:
        """Simple text analysis tool"""
        return {{
            "word_count": len(text.split()),
            "character_count": len(text),
            "contains_question": "?" in text,
            "sentiment": "neutral"  # Simplified sentiment
        }}
    
    async def process(self, input_data: Dict[str, Any]) -> Dict[str, Any]:
        """Main processing pipeline"""
        
        # Standard agent pipeline: observe -> think -> act
        observation = self.observe(input_data)
        reasoning = self.think(observation)
        action = self.act(reasoning)
        
        return {{
            "agent_id": self.agent_id,
            "observation": observation,
            "reasoning": reasoning,
            "action": action,
            "status": "completed"
        }}

# Example usage
if __name__ == "__main__":
    import asyncio
    
    agent = {agent_name.replace('-', '_').title()}Agent()
    
    async def test_agent():
        result = await agent.process({{
            "problem": "What is 2 + 2 and why?"
        }})
        print("Agent Result:", result)
    
    asyncio.run(test_agent())
''')
    
    # Create agent config
    config_file = agent_dir / "config.yaml"
    config_file.write_text(f'''agent:
  name: {agent_name}
  type: reasoning
  version: 1.0.0
  
capabilities:
  - chain_of_thought
  - basic_calculation  
  - text_analysis
  
parameters:
  max_memory_items: 100
  confidence_threshold: 0.5
  
tools:
  - calculator
  - text_analysis
''')

def create_vision_agent_template(agent_dir: Path, agent_name: str):
    """Create a vision agent template"""
    agent_file = agent_dir / f"{agent_name}.py"
    agent_file.write_text(f'''#!/usr/bin/env python3
"""
{agent_name} - Vision Agent
Basic computer vision capabilities
"""

import logging
from typing import Dict, Any

class {agent_name.replace('-', '_').title()}Agent:
    """Vision agent for image processing and analysis"""
    
    def __init__(self, agent_id: str = "{agent_name}"):
        self.agent_id = agent_id
        self.logger = logging.getLogger(f"agent.{{agent_id}}")
    
    async def process_image(self, image_data: Dict[str, Any]) -> Dict[str, Any]:
        """Process image data"""
        # Placeholder for actual vision processing
        return {{
            "agent_id": self.agent_id,
            "analysis": "Vision processing placeholder",
            "status": "completed"
        }}
''')

def create_memory_agent_template(agent_dir: Path, agent_name: str):
    """Create a memory agent template"""
    agent_file = agent_dir / f"{agent_name}.py"
    agent_file.write_text(f'''#!/usr/bin/env python3
"""
{agent_name} - Memory Agent
Memory management and retrieval capabilities
"""

import logging
from typing import Dict, Any, List

class {agent_name.replace('-', '_').title()}Agent:
    """Memory agent for information storage and retrieval"""
    
    def __init__(self, agent_id: str = "{agent_name}"):
        self.agent_id = agent_id
        self.logger = logging.getLogger(f"agent.{{agent_id}}")
        self.memory_store = []
    
    async def store_memory(self, data: Dict[str, Any]) -> bool:
        """Store information in memory"""
        self.memory_store.append(data)
        return True
    
    async def retrieve_memory(self, query: str) -> List[Dict[str, Any]]:
        """Retrieve relevant memories"""
        # Simple keyword-based retrieval
        results = [item for item in self.memory_store 
                  if query.lower() in str(item).lower()]
        return results
''')

def create_action_agent_template(agent_dir: Path, agent_name: str):
    """Create an action agent template"""
    agent_file = agent_dir / f"{agent_name}.py"
    agent_file.write_text(f'''#!/usr/bin/env python3
"""
{agent_name} - Action Agent
Execute actions based on decisions
"""

import logging
from typing import Dict, Any

class {agent_name.replace('-', '_').title()}Agent:
    """Action agent for executing decisions and commands"""
    
    def __init__(self, agent_id: str = "{agent_name}"):
        self.agent_id = agent_id
        self.logger = logging.getLogger(f"agent.{{agent_id}}")
    
    async def execute_action(self, action_data: Dict[str, Any]) -> Dict[str, Any]:
        """Execute an action"""
        return {{
            "agent_id": self.agent_id,
            "action": action_data,
            "result": "Action executed",
            "status": "completed"
        }}
''')

def main():
    """CLI entry point for nis create"""
    import argparse
    
    parser = argparse.ArgumentParser(description="Create NIS components")
    parser.add_argument("component", choices=["agent"], help="Component type to create")
    parser.add_argument("name", help="Component name")
    parser.add_argument("--type", default="reasoning", 
                       choices=["reasoning", "vision", "memory", "action"],
                       help="Agent type")
    
    args = parser.parse_args()
    
    if args.component == "agent":
        create_agent(args.name, args.type)

if __name__ == "__main__":
    main()
